CREATE SEQUENCE SEQ_TEST;

SELECT SEQ_TEST.NEXTVAL FROM DUAL;
-- 테이블에 값을 넣을때 NEXTVAL 로 넣으면 됨

SELECT SEQ_TEST.CURRVAL FROM DUAL;


--member SEQUENCE
CREATE SEQUENCE SEQ_ME_NUM
START WITH 1
INCREMENT BY 1;

-- note SEQUENCE
CREATE SEQUENCE SEQ_NO_NUM
START WITH 1
INCREMENT BY 1;

--report SEQUENCE
CREATE SEQUENCE SEQ_RE_NUM
START WITH 1
INCREMENT BY 1;

--noticephoto SEQUENCE
CREATE SEQUENCE SEQ_NO_PH_NUM
START WITH 1
INCREMENT BY 1;

--notice SEQUENCE
CREATE SEQUENCE SEQ_NO_NUM
START WITH 1
INCREMENT BY 1;

--noticecomments SEQUENCE
CREATE SEQUENCE SEQ_NO_COM_NUM
START WITH 1
INCREMENT BY 1;

--party SEQUENCE
CREATE SEQUENCE SEQ_PA_NUM
START WITH 1
INCREMENT BY 1;

--photo SEQUENCE
CREATE SEQUENCE SEQ_PH_NUM
START WITH 1
INCREMENT BY 1;

--comments SEQUENCE
CREATE SEQUENCE SEQ_COM_NUM
START WITH 1
INCREMENT BY 1;

--comphoto SEQUENCE
CREATE SEQUENCE SEQ_COM_PH_NUM
START WITH 1
INCREMENT BY 1;

--main_category SEQUENCE
CREATE SEQUENCE SEQ_CAT_NUM
START WITH 1
INCREMENT BY 1;

--sub_category SEQUENCE
CREATE SEQUENCE SEQ_SUB_CAT_NUM
START WITH 1
INCREMENT BY 1;

--payment SEQUENCE
CREATE SEQUENCE SEQ_PM_NUM
START WITH 1
INCREMENT BY 1;

--chat SEQUENCE
CREATE SEQUENCE SEQ_CHAT_NUM
START WITH 1
INCREMENT BY 1;

--qa SEQUENCE
CREATE SEQUENCE SEQ_QA_NUM
START WITH 1
INCREMENT BY 1;

--qaphoto SEQUENCE
CREATE SEQUENCE SEQ_QA_PH_NUM
START WITH 1
INCREMENT BY 1;

--qacomments SEQUENCE
CREATE SEQUENCE SEQ_QA_COM_NUM
START WITH 1
INCREMENT BY 1;