/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-21 10:52:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.party;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;
import party.model.vo.Party;

public final class party_005fview_005fclick_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("party.model.vo.Party");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("\n");

	Party party = (Party) request.getAttribute("party");
	Member member = (Member) request.getAttribute("member");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<title>party_view</title>\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"/comi/resources/css/lib/slick.min.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"/comi/resources/css/lib/slick-theme.min.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"/comi/resources/css/lib/jquery-ui.min.css\"/>\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"/comi/resources/css/main.css\"/>\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"/comi/resources/css/party_view_click.css\"/>\n");
      out.write("	<script type=\"text/javascript\" src=\"/comi/resources/js/lib/jquery.min.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src=\"/comi/resources/js/lib/slick.min.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src=\"/comi/resources/js/lib/axios.min.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src=\"/comi/resources/js/common.js\"></script>\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("    	var party = {\n");
      out.write("    			paid : Number(");
      out.print( "\"" + party.getPaNum() + "\"" );
      out.write(")\n");
      out.write("    			,meid : Number(");
      out.print( "\"" + party.getMeNum() + "\"" );
      out.write(")\n");
      out.write("    			,title : ");
      out.print( "\"" + party.getPaTitle() + "\"" );
      out.write("\n");
      out.write("    			,price : Number(");
      out.print( "\"" + party.getPaTotalAmount() + "\"" );
      out.write(")\n");
      out.write("    			,deposit : Number(");
      out.print( "\"" + party.getPaDeposit() + "\"" );
      out.write(")\n");
      out.write("    			,peoplePrice : Number(");
      out.print( "\"" + party.getPaPerAmount() + "\"" );
      out.write(")\n");
      out.write("    			\n");
      out.write("    			,title : ");
      out.print( "\"" + party.getPaTitle() + "\"" );
      out.write("\n");
      out.write("    			,contents : ");
      out.print( "\"" + party.getPaCon() + "\"" );
      out.write("\n");
      out.write("    			,enroll : ");
      out.print( "\"" + party.getPaEnroll() + "\"" );
      out.write("\n");
      out.write("    			,modDate : ");
      out.print( "\"" + party.getPaModDate() + "\"" );
      out.write("\n");
      out.write("    			,delDate : ");
      out.print( "\"" + party.getPaDelDate() + "\"" );
      out.write("\n");
      out.write("    			,act : ");
      out.print( "\"" + party.getPaAct() + "\"" );
      out.write("\n");
      out.write("    			,views : Number(");
      out.print( "\"" + party.getPaViews() + "\"" );
      out.write(")\n");
      out.write("    			,likes : Number(");
      out.print( "\"" + party.getPaLike() + "\"" );
      out.write(")\n");
      out.write("    			,count : Number(");
      out.print( "\"" + party.getPaComCount() + "\"" );
      out.write(")\n");
      out.write("				\n");
      out.write("    			,genderSet : ");
      out.print( "\"" + party.getPaGenderSet() + "\"" );
      out.write("\n");
      out.write("    			,location : ");
      out.print( "\"" + party.getPaLocation() + "\"" );
      out.write("\n");
      out.write("    			,totalNum : Number(");
      out.print( "\"" + party.getPaTotalNum() + "\"" );
      out.write(")\n");
      out.write("    			,genderLimit : ");
      out.print( "\"" + party.getPaGenderLimit() + "\"" );
      out.write("\n");
      out.write("    			,phNum : Number(");
      out.print( "\"" + party.getPhNum() + "\"" );
      out.write(")\n");
      out.write("				,category : ");
      out.print( "\"" + party.getCatNum() + "\"" );
      out.write("\n");
      out.write("    			\n");
      out.write("    		}\n");
      out.write("		var member = {\n");
      out.write("			menum : Number(");
      out.print( "\"" + member.getMeNum() + "\"" );
      out.write(")\n");
      out.write("			,name : ");
      out.print( "\"" + member.getMeName() + "\"" );
      out.write("\n");
      out.write("			,id : Number(");
      out.print( "\"" + member.getMeId() + "\"" );
      out.write(")\n");
      out.write("			,email : ");
      out.print( "\"" + member.getMeEmail() + "\"" );
      out.write("\n");
      out.write("			,phone : ");
      out.print( "\"" + member.getMePhone() + "\"" );
      out.write("\n");
      out.write("			,address : ");
      out.print( "\"" + member.getMeAdd() + "\"" );
      out.write("\n");
      out.write("			,gender : ");
      out.print( "\"" + member.getMeGender() + "\"" );
      out.write("\n");
      out.write("			,birthday : ");
      out.print( "\"" + member.getMeBDay() + "\"" );
      out.write("\n");
      out.write("			,enroll : ");
      out.print( "\"" + member.getMeEnroll() + "\"" );
      out.write("\n");
      out.write("			,nickname : ");
      out.print( "\"" + member.getMeAka() + "\"" );
      out.write("\n");
      out.write("			,like : ");
      out.print( "\"" + member.getMeLike() + "\"" );
      out.write("\n");
      out.write("			,photo : ");
      out.print( "\"" + member.getMePhotoAdd() + "\"" );
      out.write("\n");
      out.write("			,admin : ");
      out.print( "\"" + member.getMeAdmin() + "\"" );
      out.write("\n");
      out.write("			,ban : ");
      out.print( "\"" + member.getMeBan() + "\"" );
      out.write("\n");
      out.write("			,point : Number(");
      out.print( "\"" + member.getMePoint() + "\"" );
      out.write(")\n");
      out.write("		}\n");
      out.write("    </script>\n");
      out.write("	<script type=\"text/javascript\" src=\"/comi/resources/js/party_view_click.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src=\"/comi/resources/js/slick_set.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- Header Section Begin -->\n");
      out.write("    <header id=\"header_view\">    \n");
      out.write("    </header>\n");
      out.write("    <!-- Header Section End -->\n");
      out.write("\n");
      out.write("	<!-- main -->\n");
      out.write("	<main class=\"main_wrapper\">\n");
      out.write("		<div class=\"container side_margin_zero\">\n");
      out.write("\n");
      out.write("			<!-- 슬라이더 -->\n");
      out.write("			<div class=\"main_slider\">\n");
      out.write("\n");
      out.write("				<div id=\"slider_main\">\n");
      out.write("					<div>\n");
      out.write("						<div class=\"slide_box\">\n");
      out.write("							<img class=\"picture_box\" src=\"/comi/resources/images/pic01.jpg\" />\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div>\n");
      out.write("						<div class=\"slide_box\">\n");
      out.write("							<img class=\"picture_box\" src=\"/comi/resources/images/pic01.jpg\" />\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div>\n");
      out.write("						<div class=\"slide_box\">\n");
      out.write("							<img class=\"picture_box\" src=\"/comi/resources/images/pic01.jpg\" />\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("				  </div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<!-- 프로필 -->\n");
      out.write("			<section id=\"article-profile\">\n");
      out.write("				<div class=\"article-profile-box\">\n");
      out.write("					<a class=\"article-profile-link\" href=\"#\">\n");
      out.write("						<div class=\"space-between\">\n");
      out.write("							<div class=\"display-align-items-center\">\n");
      out.write("								<div id=\"article-profile-image-box\">\n");
      out.write("									<img src=\"\" />\n");
      out.write("								</div>\n");
      out.write("								<div id=\"article-profile-left\">\n");
      out.write("									<div id=\"article-nickname\"></div>\n");
      out.write("									<div id=\"article-region-name\"></div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"article-profile-right\">\n");
      out.write("								<div class=\"temperature-wrap\">\n");
      out.write("									<span>신뢰도</span>\n");
      out.write("									<span class=\"text-color text-color-03\" id=\"text-color-id\"></span>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"meters\">\n");
      out.write("									<div class=\"bar bar-color-03\" id=\"bar-color-id\"></div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"temperature-face\">\n");
      out.write("									<img id=\"temperature-face-id\" src=\"/comi/resources/images/launcher.png\" />\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("			</section>\n");
      out.write("			<!-- 프로필 end-->\n");
      out.write("			\n");
      out.write("			<!-- 게시글 -->\n");
      out.write("			<section id=\"article-description\">\n");
      out.write("				<h1 id=\"article-title\"></h1>\n");
      out.write("				<p id=\"article-category\">\n");
      out.write("				  모임 ∙\n");
      out.write("				  <span id=\"article-befordate\">\n");
      out.write("					\n");
      out.write("				  </span>\n");
      out.write("				</p>\n");
      out.write("				<p id=\"article-location\">\n");
      out.write("\n");
      out.write("				</p>\n");
      out.write("				<div id=\"article-price-box\">\n");
      out.write("					\n");
      out.write("					<div id=\"article-deposit\"></div>\n");
      out.write("					<div id=\"article-bar-box\">\n");
      out.write("						<span id=\"article-price-bar\"></span>\n");
      out.write("						<span id=\"article-deposit-bar\"></span>\n");
      out.write("					</div>\n");
      out.write("					<div id=\"article-price\"></div>\n");
      out.write("\n");
      out.write("					<div class=\"article-people-box\">\n");
      out.write("						<div id=\"article-people\"></div>\n");
      out.write("						<div id=\"article-people-price\"></div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div id=\"article-detail\">\n");
      out.write("					<p>\n");
      out.write("						\n");
      out.write("					</p>\n");
      out.write("				</div>\n");
      out.write("				<p id=\"article-counts\">\n");
      out.write("					\n");
      out.write("				</p>\n");
      out.write("			</section>\n");
      out.write("			<!-- 게시글 end-->\n");
      out.write("\n");
      out.write("			<!-- 채팅 리뷰-->\n");
      out.write("			<section id=\"chating\">\n");
      out.write("				<!--채팅 헤드-->\n");
      out.write("				<div class=\"chating-head\">\n");
      out.write("					<span class=\"chating-head-title\">엔브레드톡</span>\n");
      out.write("				</div>\n");
      out.write("				<!--채팅 헤드 end-->\n");
      out.write("				\n");
      out.write("				<!--채팅 바디-->\n");
      out.write("				<div class=\"chating-body\">\n");
      out.write("					<div class=\"chating-body-box\" id=\"chating_box\">\n");
      out.write("\n");
      out.write("						\n");
      out.write("\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<!--채팅 바디end-->\n");
      out.write("\n");
      out.write("				<!--채팅 입력-->\n");
      out.write("				<div class=\"chating-input\" id=\"chating-input-talk\">\n");
      out.write("					<div class=\"chating-input-area\">\n");
      out.write("						<textarea placeholder=\"엔브레드톡에 참여해보세요\" class=\"chating-input-area-write\"></textarea> \n");
      out.write("						<button type=\"button\" class=\"chating-post-stickerbtn\">\n");
      out.write("							<img class=\"chating-post-sendbtn-image\" src=\"/comi/resources/images/stickerbtn.png\">\n");
      out.write("						</button>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"chating-post-area\">\n");
      out.write("						<button type=\"button\" class=\"chating-post-sendbtn\">\n");
      out.write("							<img class=\"chating-post-sendbtn-image\" src=\"/comi/resources/images/sendbtn.png\">\n");
      out.write("						</button>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<!--채팅 입력 end-->\n");
      out.write("			</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("			<!--참여 버튼 버튼을 클릭해야 채팅을 할 수 있음 - 참여하지 않으면 채팅기록만 볼수 있음-->\n");
      out.write("			<section class=\"chating-allow\">\n");
      out.write("				<button class=\"chating-allow-btn\">참여</button>\n");
      out.write("			</section>\n");
      out.write("			<!--참여 버튼 end-->\n");
      out.write("\n");
      out.write("\n");
      out.write("			<!-- 공유 모임 더 보기 -->\n");
      out.write("			<section class=\"article-party-share\">\n");
      out.write("				<div class=\"article-party-share-box\">\n");
      out.write("					<div class=\"article-party-share-title\">인기공유모임</div>\n");
      out.write("					<a id=\"article-party-share-re\" href=\"/comi/views/party/party_view.html\">더보기</a>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"main_portfolio\">\n");
      out.write("					<a class=\"port_box flexBox\" href=\"/comi/views/party/party_view_click.html\">\n");
      out.write("						<div class=\"image featured\">\n");
      out.write("							<img src=\"/comi/resources/images/pic01.jpg\" alt=\"\" />\n");
      out.write("						</div>\n");
      out.write("						<div class=\"text_box\">\n");
      out.write("							<div class=\"port_box_title\">카드 판매합니다.</div>\n");
      out.write("							<div class=\"port_box_textbox\">\n");
      out.write("								<div class=\"port_box_price\">가격 : <span class=\"price_all\">230000</span></div>\n");
      out.write("								<div class=\"port_box_deposit\">예치금 : <span class=\"price_deposit\">130000</span></div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"port_box_textbox\">\n");
      out.write("								<div class=\"port_box_address\">서울시 동작구 상도로 15길</div>\n");
      out.write("								<div class=\"port_box_date\">3일전</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"port_box_textbox\">\n");
      out.write("								<div class=\"port_box_text\">인원 모집 3명</div>\n");
      out.write("								<div class=\"port_box_text\">인당 5,000원</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</a>\n");
      out.write("					<a class=\"port_box flexBox\" href=\"/comi/views/party/party_view_click.html\">\n");
      out.write("						<div class=\"image featured\">\n");
      out.write("							<img src=\"/comi/resources/images/pic01.jpg\" alt=\"\" />\n");
      out.write("						</div>\n");
      out.write("						<div class=\"text_box\">\n");
      out.write("							<div class=\"port_box_title\">카드 판매합니다.</div>\n");
      out.write("							<div class=\"port_box_textbox\">\n");
      out.write("								<div class=\"port_box_price\">가격 : <span class=\"price_all\">230000</span></div>\n");
      out.write("								<div class=\"port_box_deposit\">예치금 : <span class=\"price_deposit\">130000</span></div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"port_box_textbox\">\n");
      out.write("								<div class=\"port_box_address\">서울시 동작구 상도로 15길</div>\n");
      out.write("								<div class=\"port_box_date\">3일전</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"port_box_textbox\">\n");
      out.write("								<div class=\"port_box_text\">인원 모집 3명</div>\n");
      out.write("								<div class=\"port_box_text\">인당 5,000원</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</a>\n");
      out.write("					<a class=\"port_box flexBox\" href=\"/comi/views/party/party_view_click.html\">\n");
      out.write("						<div class=\"image featured\">\n");
      out.write("							<img src=\"/comi/resources/images/pic01.jpg\" alt=\"\" />\n");
      out.write("						</div>\n");
      out.write("						<div class=\"text_box\">\n");
      out.write("							<div class=\"port_box_title\">카드 판매합니다.</div>\n");
      out.write("							<div class=\"port_box_textbox\">\n");
      out.write("								<div class=\"port_box_price\">가격 : <span class=\"price_all\">230000</span></div>\n");
      out.write("								<div class=\"port_box_deposit\">예치금 : <span class=\"price_deposit\">130000</span></div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"port_box_textbox\">\n");
      out.write("								<div class=\"port_box_address\">서울시 동작구 상도로 15길</div>\n");
      out.write("								<div class=\"port_box_date\">3일전</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"port_box_textbox\">\n");
      out.write("								<div class=\"port_box_text\">인원 모집 3명</div>\n");
      out.write("								<div class=\"port_box_text\">인당 5,000원</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</a>\n");
      out.write("					<a class=\"port_box flexBox\" href=\"/comi/views/party/party_view_click.html\">\n");
      out.write("						<div class=\"image featured\">\n");
      out.write("							<img src=\"/comi/resources/images/pic01.jpg\" alt=\"\" />\n");
      out.write("						</div>\n");
      out.write("						<div class=\"text_box\">\n");
      out.write("							<div class=\"port_box_title\">카드 판매합니다.</div>\n");
      out.write("							<div class=\"port_box_textbox\">\n");
      out.write("								<div class=\"port_box_price\">가격 : <span class=\"price_all\">230000</span></div>\n");
      out.write("								<div class=\"port_box_deposit\">예치금 : <span class=\"price_deposit\">130000</span></div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"port_box_textbox\">\n");
      out.write("								<div class=\"port_box_address\">서울시 동작구 상도로 15길</div>\n");
      out.write("								<div class=\"port_box_date\">3일전</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"port_box_textbox\">\n");
      out.write("								<div class=\"port_box_text\">인원 모집 3명</div>\n");
      out.write("								<div class=\"port_box_text\">인당 5,000원</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</a>\n");
      out.write("					<a class=\"port_box flexBox\" href=\"/comi/views/party/party_view_click.html\">\n");
      out.write("						<div class=\"image featured\">\n");
      out.write("							<img src=\"/comi/resources/images/pic01.jpg\" alt=\"\" />\n");
      out.write("						</div>\n");
      out.write("						<div class=\"text_box\">\n");
      out.write("							<div class=\"port_box_title\">카드 판매합니다.</div>\n");
      out.write("							<div class=\"port_box_textbox\">\n");
      out.write("								<div class=\"port_box_price\">가격 : <span class=\"price_all\">230000</span></div>\n");
      out.write("								<div class=\"port_box_deposit\">예치금 : <span class=\"price_deposit\">130000</span></div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"port_box_textbox\">\n");
      out.write("								<div class=\"port_box_address\">서울시 동작구 상도로 15길</div>\n");
      out.write("								<div class=\"port_box_date\">3일전</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"port_box_textbox\">\n");
      out.write("								<div class=\"port_box_text\">인원 모집 3명</div>\n");
      out.write("								<div class=\"port_box_text\">인당 5,000원</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("			</section>\n");
      out.write("			<!-- 공유 모임 더 보기 end-->\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</main>\n");
      out.write("	\n");
      out.write("\n");
      out.write("	<!-- Footer Section Begin -->\n");
      out.write("	<footer id=\"footer_view\">	\n");
      out.write("	</footer>\n");
      out.write("	<!-- Footer Section End -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
